<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Inicio</title>
	 
	 <link rel="stylesheet" href="bootstrap4/css/bootstrap.min.css">
	 <link rel="stylesheet" type="text/css" href="css/estilo.css">
</head>
<body>

	<div class="container-fluid h-100"><!--Inicio conteiner-->
		<div class="row " >
			
			<header class="col-12 bg-primary py-3 pl-2  mb-5 h4" >
				SIGEFA
			</header>


					<div class="card-login col-4 offset-4 justify-content-center">
						<div class="card">
							<div class="card-header bg-primary">
								Login
							</div>
							<div class="card-body">
								<form action="/autenticar" method="post">
									<div class="form-group">
			                  		<input name="username" type="text" class="form-control" placeholder="Username">
			                		</div>
			               			 <div class="form-group">
			                  		<input name="senha" type="password" class="form-control" placeholder="Senha">
			                		</div>

			                		<button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>

			                		<?php if ($this->view->login=='erro') {?>
			                			<span class="form-text text-danger">
			                				Username e ou senha inválido(s)
			                			</span>
			                		<?php }?>
			                		
								</form>
							</div>
						</div>
					</div>

			
			
			<footer class="bg-primary p-3 col-12 fixed-bottom clearfix ">
				<span class="float-left">copyright @2021-Todos os direitos reservados</span>
				<span class="float-right ml-5"> version 1.0</span>
			</footer>
		</div>
	</div>	<!--/ Fim conteiner-->	
	
	

</body>
</html>