<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Administrador</title>
	 
	 <link rel="stylesheet" href="bootstrap4/css/bootstrap.min.css">
	 <link rel="stylesheet"  href="css/estilo.css">

</head>
<body >

	<div class="container-fluid h-100"><!--Inicio conteiner-->
		<div class="row h-100">

			<nav class="col-12 d-flex bg-primary py-2 pl-2 text-dark" >
				<a href="#"class="h4 navbar-brand">SIGEFA</a>	
			</nav>

			<div id="conteudos" class="w-100 d-flex"><!--Inicio conteudos-->
				<aside id="aside-conteudo" class="aside bg-dark"><!--Inicio Navegacao Lateral-->
					<div id="perfil" class="text-light">
						<img class="text-primary" src="icons/person-circle.svg" width="60px" height="60px">
						<a href="#">
							<?= $_SESSION['nome']?>
						</a>
					</div>
					<nav class="navbar p-0" >
						<ul class="navbar-nav w-100 flex-column "><!--Inicio Navegacao1-->
							<li class="nav-item">
								<a class="btn btn-block btn-primary nav-link mb-2" href="/registrar_leitura">Registrar Leitura</a> 
							</li> 
							<li class="nav-item">
								<a class="btn btn-block btn-primary  nav-link mb-2" href="/efectuar_pagamento">Efectuar Pagamento</a> 
							</li>
							<li class="nav-item">
								<a class="btn btn-block btn-primary active nav-link mb-2" href="/abrir_contrato">Abrir Contracto</a>
							</li>
						</ul>
					</nav><!--Fim Navegacao1-->
					<div class="btn d-block disabled bg-info my-3">
						Gestão de Clientes
					</div>
					<nav class="navbar p-0 " >
						<ul class="navbar-nav w-100 flex-column "><!--Inicio Navegacao2-->
							<li class="nav-item">
								<a class="btn btn-block btn-primary nav-link mb-2" href="/cadastrar_cliente">Cadastrar Clientes</a>
							</li> 
							<li class="nav-item">
								<a class="btn btn-block btn-primary nav-link mb-2" href="/actualizar_dados">Actualizar dados</a>
							</li>

							<a class="btn btn-block btn-danger my-2" href="/sair">Sair</a>
					</nav><!--Fim Navegacao2-->

					
					
					
				</aside><!--Fim navegacao-lateral-->

				<div id="conteudo-principal" class="h-100"><!--Inicio conteudos-Principal-->
					 <h1>Abrir Contrato</h1>

					 <?php
						if (isset($this->view->sucesso)) {
							if ($this->view->sucesso) {
							?> <h4 class="text-success col-6 offset-6">Contrato aberto com sucesso</h4>  <?Php	
							}
					 	}

						?>
					 <hr>
					 
					
						<form action="/registrar_contador" method="post">

							<?php if(isset($this->view->contadorInvalido)){

										if (isset($this->view->registroSucesso)){
											
											if ($this->view->registroSucesso){?>
												
												<small class="text-success ml-3V">Contador cadastrado com sucesso</small>

											<?php }else  { ?>
												<small class="text-danger ml-3">Este campo não pode estar vazio</small>
											<?php }
										}
										
									}
							 ?>
								


							<div class="d-flex  col-6">
								
							<input class="form-control" type="number" name="contador" 		placeholder="Digite o número do contador" value="<?=$this->view->contador?>">
								<button class="btn btn-primary"  type="submit" >Registrar</button>
							</div>
						
								
									<div class="form-inline col-6 offset-6 my-2">
										<input class="form-control col-8 prepend" placeholder="Pesquisar por nome ou username" type="text" name="pesquisar" value="<?=$this->view->pesquisa?>">

										<input  class="btn  btn-primary col-4" type="submit" value="Pesquisar">
									</div>
						</form>
						
						<div class="">
							
							<form class="" action="/registrar_contrato" method="post">
								<div class=" d-flex ">
								
								<div class="col-6">
								<h4>Dados do contrato</h4>
									<div d-flex >

										

									<?php if(isset($this->view->showcont)) {  ?>

											<div class="form-group form-inline col-12">

										 		<div class="input-group col-12">
										           <div class="input-group-prepend">
								               		<span class="input-group-text bg-info">Contador</span>
								           		   </div>
			           								
								           		   <input type="text" readonly name="numero_contador" value="<?=$this->view->contador?>">
			           								
			       								</div> 
					       					</div>

									<?php }	?>

								

									<div class="form-group form-inline col-12">

								 		<div class="input-group col-12">
								           <div class="input-group-prepend">
								               <span class="input-group-text bg-info">Bairro</span>
								           </div>
			           					<input name="bairro" value=""class="form-control" type="text" placeholder="Digite o bairro">
			       						</div> 
					       			</div>

					       			<div class="form-group form-inline col-12">

								 		<div class="input-group col-12">
								           <div class="input-group-prepend">
								               <span class="input-group-text bg-info">Quart</span>
								           </div>
			           					<input name="quarteirao" value=""class="form-control w-75" type="text" placeholder="Digite quarteirão">
			       						</div> 
					       			</div>

					       			<div class="form-group form-inline col-12">

								 		<div class="input-group col-12">
								           <div class="input-group-prepend">
								               <span class="input-group-text bg-info">Casa</span>
								           </div>
			           					<input name="casa" value=""class="form-control" type="text" placeholder="Digite número da casa">
			       						</div> 
					       			</div>



					       			<div class="form-group  col-12">
					       				
					       				<div class="col-12">
						       				<label class="h6" for="tipo_contrato">Classificação do contrato</label><br>
								       		<input type="radio" id="tipo_contrato" name="contrato_tipo" value="domestico"> <span class="mr-2">Doméstico</span>

								       		<input type="radio"  id="tipo_contrato" name="contrato_tipo" value="empresarial"> <span>Empresarial</span>
					       				</div>
					       			</div>

					       			
						       		</div>

						       		

									
								</div>
								
								<div class="col-6">
									<h4>Associar com o Cliente</h4>
								
								<table class="table table-striped">

										<thead class="">
											<th>Nome</th>
											<th>Apelido</th>
											<th>Cidade</th>
											<th>Sexo</th>
											<th>Selecionar</th>
										</thead>


									<?php 
										if(isset($this->view->clientes)){

											 foreach ($this->view->clientes as $i=>$cliente) {?>

												<tbody>
													<td><?=$cliente['cliente_nome']?></td>
													<td><?=$cliente['cliente_apelido']?></td>
													<td><?=$cliente['cliente_cidade']?></td>
													<td><?=$cliente['cliente_sexo']?></td>
													<td>
													<form action="/registrar_contrato" method="post">
										  			  <input type="checkbox" name="cliente" value="<?=$cliente['cliente_cod']?>"/>	
													</form>
								
													</td>
												</tbody>
										
									<?php }
										}
									?>

							</table>
				
									<input  class="btn  btn-primary col-4 offset-8 mb-3 " type="submit" value="Abrir Contracto">
								</div>
								</div>
								
							</form>

					
						
						</div>			

					
					 

				</div><!--Fim conteudos-Principal-->
			</div><!--Fim conteudos-->
		<footer class="bg-primary text-dark p-3 col-12  clearfix ">
				<span class="float-left">copyright @2021-Todos os direitos reservados</span>
				<span class="float-right ml-5"> version 1.0</span>
			</footer>		
			
			
		</div>
	</div>	<!--Inicio conteiner-->	

	<

</body>
</html>