<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Administrador</title>
	 
	 <link rel="stylesheet" href="bootstrap4/css/bootstrap.min.css">
	 <link rel="stylesheet"  href="css/estilo.css">

</head>
<body >

	<div class="container-fluid h-100"><!--Inicio conteiner-->
		<div class="row h-100">

			<nav class="col-12 d-flex bg-primary py-2 pl-2 text-dark" >
				<a href="#"class="h4 navbar-brand">SIGEFA</a>	
			</nav>

			<div id="conteudos" class="w-100 d-flex"><!--Inicio conteudos-->
				<aside id="aside-conteudo" class="aside bg-dark"><!--Inicio Navegacao Lateral-->
					<div id="perfil" class="text-light">
						<img class="text-primary" src="icons/person-circle.svg" width="60px" height="60px">
						<a href="#">
							<?= $_SESSION['nome']?>
						</a>
					</div>
					<nav class="navbar p-0" >
						<ul class="navbar-nav w-100 flex-column "><!--Inicio Navegacao1-->
							<li class="nav-item">
								<a class="btn btn-block btn-primary  nav-link mb-2" href="/registrar_leitura">Registrar Leitura</a> 
							</li> 
							<li class="nav-item">
								<a class="btn btn-block btn-primary  nav-link mb-2" href="/efectuar_pagamento">Efectuar Pagamento</a> 
							</li>
							<li class="nav-item">
								<a class="btn btn-block btn-primary  nav-link mb-2" href="/abrir_contrato">Abrir Contracto</a>
							</li>
						</ul>
					</nav><!--Fim Navegacao1-->
					<div class="btn d-block disabled bg-info my-3">
						Gestão de Clientes
					</div>
					<nav class="navbar p-0 " >
						<ul class="navbar-nav w-100 flex-column "><!--Inicio Navegacao2-->
							<li class="nav-item">
								<a class="btn btn-block btn-primary nav-link  mb-2" href="/cadastrar_cliente">Cadastrar Clientes</a>
							</li> 
							<li class="nav-item">
								<a class="btn btn-block btn-primary nav-link mb-2" href="/actualizar_dados">Actualizar dados</a>
							</li>

							<a class="btn btn-block btn-danger my-2" href="/sair">Sair</a>
					</nav><!--Fim Navegacao2-->

					
					
					
				</aside><!--Fim navegacao-lateral-->

				<div id="conteudo-principal" class="h-100"><!--Inicio conteudos-Principal-->
					 <h1>Registrar Leitura</h1>

					 	<?php if (isset($this->view->leituraInserida)) {?>
					 	 	<h4 class="col-6 offset-6 text-success"> Leitura registrada com sucesso</h4>
					 	 
					 	 <?php }?>

					 	
					
					  <hr>

					 <form action="/buscar_contador" method="post" class="col-6">
					 	<div class=" input-group ">
			 			    <input class="form-control  append" placeholder="Número do contador" type="number" name="numero" value="<?=$this->view->numeroContador?>">
							<div  class="input-group-append">
				 				<button class="btn btn-primary">Pesquisar</button>
							</div>
										
						</div>
				        
   					 </form>

   					 <?php if (isset($this->view->contadorExiste)) {
							if ($this->view->contadorExiste) {
								?> 

   					 <div class="d-flex">

   					 	<div class="col-6">
   					 		<form action="inserir_leitura" method="post">
   					 			<div class="form-group">
						            <label for="leitura">Leitura actual</label>
						            <input class="form-control" type="number" name="leitura" id="leitura" placeholder="Digite a leitura actual">
						        </div>

						        <input type="hidden" name="contador" value="<?=$this->view->dados['numero_contador'] ?>">

						     <div  class="input-group">
				 				<button class="btn btn-primary">Registrar</button>
							</div>
   					 	
   						</div>

	   					 <div class="col-6 ">

	   					 	

								<div id="cliente" class="mt-5 ">
								<span class="h5">Dados do Cliente</span><br>
								<hr>
								<span class="text-dark h6">Nome:</span> <?= $this->view->dados['cliente_nome']." ".$this->view->dados['cliente_apelido'] ?><br>
								
								<span class="text-dark h6">Bairro:</span>
								 <?= $this->view->dados['cliente_bairro']?><br>
								<span class="text-dark h6">Quarteirao:</span> <?= $this->view->dados['cliente_quarteirao']?><br>
								<span class="text-dark h6">Casa:</span> <?= $this->view->dados['cliente_casa']?><br>
							</div> 
							
	   					 	
	   					 </div>
   					 	
   					 </div>

   					 <?php }
						}?>
   					 
   					 

   					 
					
					
					 

				</div><!--Fim conteudos-Principal-->
			</div><!--Fim conteudos-->
		<footer class="bg-primary text-dark p-3 col-12 clearfix ">
				<span class="float-left">copyright @2021-Todos os direitos reservados</span>
				<span class="float-right ml-5"> version 1.0</span>
			</footer>		
			
			
		</div>
	</div>	<!--Inicio conteiner-->	

</body>
</html>