<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Inicio</title>
	 
	 <link rel="stylesheet" href="bootstrap4/css/bootstrap.min.css">
	 <link rel="stylesheet" type="text/css" href="css/estilo.css">
</head>
<body>

	<div class="container-fluid h-100"><!--Inicio conteiner-->
		<div class="row " >
			
			<header class="col-12 bg-primary py-3 pl-2 text-primary mb-5 h4" >
				SIGEFA
			</header>
 
				<div class="container-fluid">

					<div class=" col-6 offset-3">
						<h1 class="text-success text-lg-center">SIGEFA</h1>

						<h4 class="text-success">Sucesso</h4>
						
						<p>
							Leitura registrada com sucesso
						</p>

						<a class="btn btn-info" href="">Gerar Factura</a>
						<a class="btn btn-primary ml-5" href="/registrar_leitura">Voltar</a>
					</div>
					
					
					
				</div>

					

			
			<footer class="bg-primary  p-3 col-12 fixed-bottom clearfix ">
				<span class="float-left">copyright @2021-Todos os direitos reservados</span>
				<span class="float-right ml-5"> version 1.0</span>
			</footer>
		</div>
	</div>	<!--/ Fim conteiner-->	
	
	

</body>
</html>